import type {
  Appointment,
  Business,
  Customer,
  Notification,
  Service,
  Staff,
  WorkingHours,
} from '@/lib/types';

export const mockBusinesses: Business[] = [
  {
    id: 'b1',
    owner_id: 'u-owner-1',
    name: 'Luxe Hair Studio',
    slug: 'luxe-hair-studio',
    description:
      'A premium hair salon offering cuts, coloring, and styling by award-winning stylists.',
    category: 'Hair Salon',
    address: '123 Main Street',
    city: 'San Francisco',
    phone: '(415) 555-0100',
    email: 'hello@luxehair.com',
    logo_url: null,
    cover_url: null,
    primary_color: '#111827',
    secondary_color: '#f8fafc',
    accent_color: '#c59d5f',
    heading_color: '#0f172a',
    body_color: '#334155',
    muted_color: '#64748b',
    button_text_color: '#ffffff',
    button_hover_bg_color: '#0d9488',
    button_hover_text_color: '#ffffff',
    nav_text_color: '#475569',
    card_text_color: '#1e293b',
    status: 'approved',
    rating: 4.8,
    review_count: 124,
    subscription_plan: 'pro',
    subscription_status: 'active',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'b2',
    owner_id: 'u-owner-2',
    name: 'The Gentleman Barber',
    slug: 'the-gentleman-barber',
    description: 'Classic barbering with a modern twist. Walk-ins welcome.',
    category: 'Barber',
    address: '456 Oak Avenue',
    city: 'San Francisco',
    phone: '(415) 555-0200',
    email: 'book@gentlemanbarber.com',
    logo_url: null,
    cover_url: null,
    primary_color: '#111827',
    secondary_color: '#f8fafc',
    accent_color: '#c59d5f',
    heading_color: '#0f172a',
    body_color: '#334155',
    muted_color: '#64748b',
    button_text_color: '#ffffff',
    button_hover_bg_color: '#0d9488',
    button_hover_text_color: '#ffffff',
    nav_text_color: '#475569',
    card_text_color: '#1e293b',
    status: 'approved',
    rating: 4.9,
    review_count: 89,
    subscription_plan: 'starter',
    subscription_status: 'active',
    created_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 'b3',
    owner_id: 'u-owner-3',
    name: 'Bloom Beauty Lounge',
    slug: 'bloom-beauty-lounge',
    description: 'Full-service beauty lounge offering facials, waxing, and makeup.',
    category: 'Beauty',
    address: '789 Flower Street',
    city: 'Oakland',
    phone: '(510) 555-0300',
    email: 'info@bloombeauty.com',
    logo_url: null,
    cover_url: null,
    primary_color: '#111827',
    secondary_color: '#f8fafc',
    accent_color: '#c59d5f',
    heading_color: '#0f172a',
    body_color: '#334155',
    muted_color: '#64748b',
    button_text_color: '#ffffff',
    button_hover_bg_color: '#0d9488',
    button_hover_text_color: '#ffffff',
    nav_text_color: '#475569',
    card_text_color: '#1e293b',
    status: 'approved',
    rating: 4.7,
    review_count: 56,
    subscription_plan: 'pro',
    subscription_status: 'active',
    created_at: '2024-03-10T10:00:00Z',
  },
  {
    id: 'b4',
    owner_id: 'u-owner-4',
    name: 'Sharp Cuts Barbershop',
    slug: 'sharp-cuts-barbershop',
    description: 'Neighborhood barbershop with skilled stylists and fair prices.',
    category: 'Barber',
    address: '321 Pine Street',
    city: 'San Francisco',
    phone: '(415) 555-0400',
    email: null,
    logo_url: null,
    cover_url: null,
    primary_color: '#111827',
    secondary_color: '#f8fafc',
    accent_color: '#c59d5f',
    heading_color: '#0f172a',
    body_color: '#334155',
    muted_color: '#64748b',
    button_text_color: '#ffffff',
    button_hover_bg_color: '#0d9488',
    button_hover_text_color: '#ffffff',
    nav_text_color: '#475569',
    card_text_color: '#1e293b',
    status: 'pending',
    rating: 0,
    review_count: 0,
    subscription_plan: 'free',
    subscription_status: 'trialing',
    created_at: '2024-08-01T10:00:00Z',
  },
];

export const mockServices: Service[] = [
  {
    id: 's1',
    business_id: 'b1',
    name: 'Classic Haircut',
    description: 'A precision cut tailored to your style.',
    duration_minutes: 45,
    price: 45,
    category: 'Hair',
    active: true,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 's2',
    business_id: 'b1',
    name: 'Hair Coloring',
    description: 'Full-color treatment with premium products.',
    duration_minutes: 120,
    price: 120,
    category: 'Color',
    active: true,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 's3',
    business_id: 'b1',
    name: 'Blowout & Style',
    description: 'Wash, blow-dry, and style for any occasion.',
    duration_minutes: 60,
    price: 65,
    category: 'Styling',
    active: true,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 's4',
    business_id: 'b2',
    name: 'Men’s Haircut',
    description: 'Classic or modern cut with hot towel finish.',
    duration_minutes: 30,
    price: 30,
    category: 'Hair',
    active: true,
    created_at: '2024-02-25T10:00:00Z',
  },
  {
    id: 's5',
    business_id: 'b2',
    name: 'Beard Trim',
    description: 'Shape and trim for a clean look.',
    duration_minutes: 20,
    price: 18,
    category: 'Beard',
    active: true,
    created_at: '2024-02-25T10:00:00Z',
  },
  {
    id: 's6',
    business_id: 'b3',
    name: 'Signature Facial',
    description: 'Deep-cleansing facial customized to your skin.',
    duration_minutes: 60,
    price: 85,
    category: 'Skincare',
    active: true,
    created_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 's7',
    business_id: 'b3',
    name: 'Full Makeup',
    description: 'Professional makeup for events and photoshoots.',
    duration_minutes: 45,
    price: 70,
    category: 'Makeup',
    active: true,
    created_at: '2024-03-15T10:00:00Z',
  },
];

export const mockStaff: Staff[] = [
  {
    id: 'st1',
    business_id: 'b1',
    user_id: 'u-staff-1',
    full_name: 'Maria Rodriguez',
    email: 'maria@luxehair.com',
    phone: '(415) 555-1100',
    role_title: 'Senior Stylist',
    bio: '10+ years specializing in color and balayage.',
    avatar_url: null,
    active: true,
    created_at: '2024-01-16T10:00:00Z',
  },
  {
    id: 'st2',
    business_id: 'b1',
    user_id: 'u-staff-2',
    full_name: 'James Chen',
    email: 'james@luxehair.com',
    phone: '(415) 555-1101',
    role_title: 'Stylist',
    bio: 'Expert in men’s cuts and modern styling.',
    avatar_url: null,
    active: true,
    created_at: '2024-01-16T10:00:00Z',
  },
  {
    id: 'st3',
    business_id: 'b2',
    user_id: 'u-staff-3',
    full_name: 'Tony Russo',
    email: 'tony@gentlemanbarber.com',
    phone: '(415) 555-1200',
    role_title: 'Master Barber',
    bio: 'Classic barbering, straight razor shaves.',
    avatar_url: null,
    active: true,
    created_at: '2024-02-21T10:00:00Z',
  },
  {
    id: 'st4',
    business_id: 'b3',
    user_id: 'u-staff-4',
    full_name: 'Aisha Patel',
    email: 'aisha@bloombeauty.com',
    phone: '(510) 555-1300',
    role_title: 'Esthetician',
    bio: 'Certified esthetician specializing in facials.',
    avatar_url: null,
    active: true,
    created_at: '2024-03-11T10:00:00Z',
  },
];

const defaultHours = (staffId: string): WorkingHours[] =>
  [1, 2, 3, 4, 5].map((day) => ({
    id: `${staffId}-wh-${day}`,
    staff_id: staffId,
    day_of_week: day,
    start_time: '09:00',
    end_time: '17:00',
    is_working: true,
  }));

export const mockWorkingHours: WorkingHours[] = [
  ...defaultHours('st1'),
  ...defaultHours('st2'),
  ...defaultHours('st3'),
  ...defaultHours('st4'),
];

const today = new Date();
const isoDate = (daysFromNow: number, hour: number, min = 0) => {
  const d = new Date(today);
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
};

export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    business_id: 'b1',
    service_id: 's1',
    staff_id: 'st1',
    customer_id: 'c1',
    customer_name: 'Sarah Johnson',
    customer_email: 'sarah@example.com',
    customer_phone: '(415) 555-2001',
    service_name: 'Classic Haircut',
    staff_name: 'Maria Rodriguez',
    start_time: isoDate(0, 10, 0),
    end_time: isoDate(0, 10, 45),
    duration_minutes: 45,
    price: 45,
    status: 'confirmed',
    notes: null,
    created_at: isoDate(-2, 9),
    updated_at: isoDate(-2, 9),
  },
  {
    id: 'a2',
    business_id: 'b1',
    service_id: 's2',
    staff_id: 'st1',
    customer_id: 'c2',
    customer_name: 'Emily Davis',
    customer_email: 'emily@example.com',
    customer_phone: '(415) 555-2002',
    service_name: 'Hair Coloring',
    staff_name: 'Maria Rodriguez',
    start_time: isoDate(0, 13, 0),
    end_time: isoDate(0, 15, 0),
    duration_minutes: 120,
    price: 120,
    status: 'confirmed',
    notes: 'Going lighter for summer.',
    created_at: isoDate(-3, 14),
    updated_at: isoDate(-1, 11),
  },
  {
    id: 'a3',
    business_id: 'b1',
    service_id: 's3',
    staff_id: 'st2',
    customer_id: 'c3',
    customer_name: 'Michael Brown',
    customer_email: 'michael@example.com',
    customer_phone: '(415) 555-2003',
    service_name: 'Blowout & Style',
    staff_name: 'James Chen',
    start_time: isoDate(0, 15, 0),
    end_time: isoDate(0, 16, 0),
    duration_minutes: 60,
    price: 65,
    status: 'pending',
    notes: null,
    created_at: isoDate(0, 8),
    updated_at: isoDate(0, 8),
  },
  {
    id: 'a4',
    business_id: 'b1',
    service_id: 's1',
    staff_id: 'st2',
    customer_id: 'c4',
    customer_name: 'Jessica Wilson',
    customer_email: 'jessica@example.com',
    customer_phone: '(415) 555-2004',
    service_name: 'Classic Haircut',
    staff_name: 'James Chen',
    start_time: isoDate(1, 11, 0),
    end_time: isoDate(1, 11, 45),
    duration_minutes: 45,
    price: 45,
    status: 'confirmed',
    notes: null,
    created_at: isoDate(-1, 10),
    updated_at: isoDate(-1, 10),
  },
  {
    id: 'a5',
    business_id: 'b1',
    service_id: 's2',
    staff_id: 'st1',
    customer_id: 'c1',
    customer_name: 'Sarah Johnson',
    customer_email: 'sarah@example.com',
    customer_phone: '(415) 555-2001',
    service_name: 'Hair Coloring',
    staff_name: 'Maria Rodriguez',
    start_time: isoDate(2, 14, 0),
    end_time: isoDate(2, 16, 0),
    duration_minutes: 120,
    price: 120,
    status: 'confirmed',
    notes: null,
    created_at: isoDate(0, 9),
    updated_at: isoDate(0, 9),
  },
  {
    id: 'a6',
    business_id: 'b1',
    service_id: 's1',
    staff_id: 'st1',
    customer_id: 'c5',
    customer_name: 'David Lee',
    customer_email: 'david@example.com',
    customer_phone: '(415) 555-2005',
    service_name: 'Classic Haircut',
    staff_name: 'Maria Rodriguez',
    start_time: isoDate(-1, 12, 0),
    end_time: isoDate(-1, 12, 45),
    duration_minutes: 45,
    price: 45,
    status: 'completed',
    notes: null,
    created_at: isoDate(-3, 10),
    updated_at: isoDate(-1, 13),
  },
  {
    id: 'a7',
    business_id: 'b1',
    service_id: 's3',
    staff_id: 'st2',
    customer_id: 'c6',
    customer_name: 'Anna Garcia',
    customer_email: 'anna@example.com',
    customer_phone: '(415) 555-2006',
    service_name: 'Blowout & Style',
    staff_name: 'James Chen',
    start_time: isoDate(-2, 15, 0),
    end_time: isoDate(-2, 16, 0),
    duration_minutes: 60,
    price: 65,
    status: 'completed',
    notes: null,
    created_at: isoDate(-5, 10),
    updated_at: isoDate(-2, 16),
  },
  {
    id: 'a8',
    business_id: 'b1',
    service_id: 's1',
    staff_id: 'st1',
    customer_id: 'c7',
    customer_name: 'Robert Taylor',
    customer_email: 'robert@example.com',
    customer_phone: '(415) 555-2007',
    service_name: 'Classic Haircut',
    staff_name: 'Maria Rodriguez',
    start_time: isoDate(-3, 11, 0),
    end_time: isoDate(-3, 11, 45),
    duration_minutes: 45,
    price: 45,
    status: 'cancelled',
    notes: 'Customer cancelled — schedule conflict.',
    created_at: isoDate(-6, 10),
    updated_at: isoDate(-4, 9),
  },
  {
    id: 'a9',
    business_id: 'b1',
    service_id: 's2',
    staff_id: 'st1',
    customer_id: 'c2',
    customer_name: 'Emily Davis',
    customer_email: 'emily@example.com',
    customer_phone: '(415) 555-2002',
    service_name: 'Hair Coloring',
    staff_name: 'Maria Rodriguez',
    start_time: isoDate(-4, 14, 0),
    end_time: isoDate(-4, 16, 0),
    duration_minutes: 120,
    price: 120,
    status: 'no_show',
    notes: 'Did not show up; no call.',
    created_at: isoDate(-8, 10),
    updated_at: isoDate(-4, 17),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    business_id: 'b1',
    user_id: 'u-cust-1',
    full_name: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '(415) 555-2001',
    notes: 'Prefers Maria. Allergic to ammonia.',
    total_visits: 8,
    last_visit: isoDate(-1, 12),
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'c2',
    business_id: 'b1',
    user_id: 'u-cust-2',
    full_name: 'Emily Davis',
    email: 'emily@example.com',
    phone: '(415) 555-2002',
    notes: null,
    total_visits: 5,
    last_visit: isoDate(-4, 14),
    created_at: '2024-02-15T10:00:00Z',
  },
  {
    id: 'c3',
    business_id: 'b1',
    user_id: 'u-cust-3',
    full_name: 'Michael Brown',
    email: 'michael@example.com',
    phone: '(415) 555-2003',
    notes: null,
    total_visits: 3,
    last_visit: isoDate(-7, 15),
    created_at: '2024-03-01T10:00:00Z',
  },
  {
    id: 'c4',
    business_id: 'b1',
    user_id: null,
    full_name: 'Jessica Wilson',
    email: 'jessica@example.com',
    phone: '(415) 555-2004',
    notes: 'Wedding prep — book 2 weeks ahead.',
    total_visits: 2,
    last_visit: isoDate(-14, 11),
    created_at: '2024-04-01T10:00:00Z',
  },
  {
    id: 'c5',
    business_id: 'b1',
    user_id: null,
    full_name: 'David Lee',
    email: 'david@example.com',
    phone: '(415) 555-2005',
    notes: null,
    total_visits: 4,
    last_visit: isoDate(-1, 12),
    created_at: '2024-04-10T10:00:00Z',
  },
  {
    id: 'c6',
    business_id: 'b1',
    user_id: null,
    full_name: 'Anna Garcia',
    email: 'anna@example.com',
    phone: '(415) 555-2006',
    notes: null,
    total_visits: 1,
    last_visit: isoDate(-2, 15),
    created_at: '2024-05-01T10:00:00Z',
  },
  {
    id: 'c7',
    business_id: 'b1',
    user_id: null,
    full_name: 'Robert Taylor',
    email: 'robert@example.com',
    phone: '(415) 555-2007',
    notes: 'Cancelled last appointment.',
    total_visits: 2,
    last_visit: isoDate(-10, 11),
    created_at: '2024-05-15T10:00:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    user_id: 'u-owner-1',
    business_id: 'b1',
    type: 'booking',
    title: 'New booking request',
    message: 'Michael Brown requested a Blowout & Style today at 3:00 PM.',
    read: false,
    created_at: isoDate(0, 8),
  },
  {
    id: 'n2',
    user_id: 'u-owner-1',
    business_id: 'b1',
    type: 'reminder',
    title: 'Upcoming appointment',
    message: 'Sarah Johnson’s coloring is in 2 days.',
    read: false,
    created_at: isoDate(0, 7),
  },
  {
    id: 'n3',
    user_id: 'u-owner-1',
    business_id: 'b1',
    type: 'review',
    title: 'New 5-star review',
    message: 'David Lee left a 5-star review.',
    read: true,
    created_at: isoDate(-1, 18),
  },
  {
    id: 'n4',
    user_id: 'u-owner-1',
    business_id: 'b1',
    type: 'system',
    title: 'Weekly summary ready',
    message: 'Your weekly analytics summary is available.',
    read: true,
    created_at: isoDate(-1, 9),
  },
];

export const mockTimeSlots = [
  { start_time: '09:00', end_time: '09:45', available: true },
  { start_time: '10:00', end_time: '10:45', available: false },
  { start_time: '11:00', end_time: '11:45', available: true },
  { start_time: '13:00', end_time: '13:45', available: true },
  { start_time: '14:00', end_time: '14:45', available: false },
  { start_time: '15:00', end_time: '15:45', available: true },
  { start_time: '16:00', end_time: '16:45', available: true },
];
